name: Publish

on:
  release:
    types: [published]

env:
  UV_PYTHON: 3.13

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/emmett55
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Build distributions
        run: |
          uv build
      - name: Publish package to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
