name: Tests

on:
  push:
    branches:
      - "master"
  pull_request:
    types: [opened, synchronize]
    branches:
      - master

jobs:
  Linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9, '3.10', '3.11', '3.12', '3.13']

    env:
      UV_PYTHON: ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install dependencies
      run: |
        uv sync --dev
    - name: Test
      run: |
        uv run pytest -v tests

  MacOS:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9, '3.10', '3.11', '3.12', '3.13']

    env:
      UV_PYTHON: ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install dependencies
      run: |
        uv sync --dev
    - name: Test
      run: |
        uv run pytest -v tests

  Windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9, '3.10', '3.11', '3.12', '3.13']

    env:
      UV_PYTHON: ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install dependencies
      shell: bash
      run: |
        uv sync --dev
    - name: Test
      shell: bash
      run: |
        uv run pytest -v tests
